include:
  - project: 'diehlabs/devops/cicd-templates'
    file: '/infra/terraform-matrix.yml'
    ref: v0.4-stable

variables:
  TF_CLI_VERSION: '1.3.6'
  GITLAB_TOKEN: $TERRAFORM_GITLAB_TOKEN

# -----------------------------------------------------------------------------
#  Non Prod
# -----------------------------------------------------------------------------
plan_nonprod:
  extends: .tf_plan
  allow_failure: true
  variables:
    TF_VARS_FILE: mgt-nonprod
    TF_WORKSPACE: $TF_VARS_FILE

apply_nonprod:
  extends: .tf_plan
  needs: [plan_nonprod]
  variables:
    TF_VARS_FILE: mgt-nonprod
    TF_WORKSPACE: $TF_VARS_FILE

# -----------------------------------------------------------------------------
#  Production
# -----------------------------------------------------------------------------
plan_production:
  extends: .tf_plan
  allow_failure: true
  variables:
    TF_VARS_FILE: mgt-production
    TF_WORKSPACE: $TF_VARS_FILE

apply_production:
  extends: .tf_plan
  needs: [plan_production]
  variables:
    TF_VARS_FILE: mgt-production
    TF_WORKSPACE: $TF_VARS_FILE
