# -----------------------------------------------------------------------------
# Requirements:
# jq
# custom scripts, expected to be included in docker image
# -----------------------------------------------------------------------------
include:
  - project: 'verituity/devops/cicd-templates'
    file: '/infra/terraform.yml'
    ref: v0.4-stable

variables:
  TF_CLI_VERSION: '1.3.3'
